export const SET_JOB_VIEW_TYPE="SET_JOB_VIEW_TYPE";

export const GET_SECTORS_REQUEST = "GET_SECTORS_REQUEST";
export const GET_SECTORS_SUCCESS = "GET_SECTORS_SUCCESS";
export const GET_SECTORS_FAILURE = "GET_SECTORS_FAILURE";

export const ADD_CANDIDATE_REQUEST = "ADD_CANDIDATE_REQUEST";
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_FAILURE = "ADD_CANDIDATE_FAILURE";

export const HANDLE_CANDIDATE_APPLY_MODAL = "HANDLE_CANDIDATE_APPLY_MODAL";

export const GET_LIBRARYS_REQUEST = "GET_LIBRARYS_REQUEST";
export const GET_LIBRARYS_SUCCESS = "GET_LIBRARYS_SUCCESS";
export const GET_LIBRARYS_FAILURE = "GET_LIBRARYS_FAILURE";

export const GET_PROOFS_REQUEST="GET_PROOFS_REQUEST";
export const GET_PROOFS_SUCCESS="GET_PROOFS_SUCCESS";
export const GET_PROOFS_FAILURE="GET_PROOFS_FAILURE";

export const GET_DESIGNATIONS_REQUEST = "GET_DESIGNATIONS_REQUEST";
export const GET_DESIGNATIONS_SUCCESS = "GET_DESIGNATIONS_SUCCESS";
export const GET_DESIGNATIONS_FAILURE = "GET_DESIGNATIONS_FAILURE";

export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";

export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";

export const GET_CURRENCY_REQUEST = "GET_CURRENCY_REQUEST";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";

export const ADD_PARTNER_REQUEST = "ADD_PARTNER_REQUEST";
export const ADD_PARTNER_SUCCESS = "ADD_PARTNER_SUCCESS";
export const ADD_PARTNER_FAILURE = "ADD_PARTNER_FAILURE";

export const ADD_EMAIL_REQUEST="ADD_EMAIL_REQUEST";
export const ADD_EMAIL_SUCCESS="ADD_EMAIL_SUCCESS";
export const ADD_EMAIL_FAILURE="ADD_EMAIL_FAILURE";

export const HANDLE_EMAIL_FORM_MODAL="HANDLE_EMAIL_FORM_MODAL";

export const GET_JOB_CARD_REQUEST="GET_JOB_CARD_REQUEST";
export const GET_JOB_CARD_SUCCESS="GET_JOB_CARD_SUCCESS";
export const GET_JOB_CARD_FAILURE="GET_JOB_CARD_FAILURE";
export const SET_CARD_DATA="SET_CARD_DATA";

export const ADD_CANDIDATE_PROCESS_REQUEST="ADD_CANDIDATE_PROCESS_REQUEST";
export const ADD_CANDIDATE_PROCESS_SUCCESS="ADD_CANDIDATE_PROCESS_SUCCESS";
export const ADD_CANDIDATE_PROCESS_FAILURE="ADD_CANDIDATE_PROCESS_FAILURE";